---
title: "ViralLoaadSEM"
author: "Adejumo Ridwan Suleiman"
date: "`r Sys.Date()`"
output: pdf_document
---

#
```{r}
library(mvnormalTest)
library(lavaan)
library(dplyr)
library(tidyr)
library(lavaanPlot)
```

# Load the Data
```{r}
VL_data <- haven::read_sav("C:/Users/User/Documents/ViralLoadSEM/Adherence.sav")
```

# Data Cleaning
```{r}
data <- VL_data %>% 
  select(Agecat, Sex, Durationcat2, ARTregimen, PreEACVLcat, 
         Forgot, Beliefs, Sideffects, PhysicalIllness, Substanceuse, Depression, Pillburden, LostRanout, Transport, Scheduling, DisclosureFear, Partner, DrugStock, Stigma,
         Education, Counselling, PeerSupport, Extendedpickup,
         PillBox, Calender, Incentives, ARVswallowing, PhoneCalls, SMS, Alarms) %>% 
  rename(AGE = Agecat,
         Dur = Durationcat2,
         ART = ARTregimen,
         PVL = PreEACVLcat,
         b1 = Forgot,
         b2 = Beliefs,
         b3 = Sideffects,
         b4 = PhysicalIllness,
         b5 = Substanceuse,
         b6 = Depression,
         b7 = Pillburden,
         b8 = LostRanout,
         b9 = Transport,
         b10 = Scheduling,
         b11 = DisclosureFear,
         b12 = Partner,
         b13 = DrugStock,
         b14 = Stigma,
         s1 = Education,
         s2 = Counselling,
         s3 = PeerSupport,
         s4 = Extendedpickup,
         t1 = PillBox,
         t2 = Calender,
         t3 = Incentives,
         t4 = ARVswallowing,
         t5 = PhoneCalls,
         t6 = SMS,
         t7 = Alarms) %>% 
  drop_na()#%>% 
  #mutate_if(is.numeric, as_factor)
```

# Data Summary
```{r}
skimr::skim(data)
```

# Correlation Test
## Beliefs
```{r}
data %>% 
  select(AGE:t7) %>% 
  rstatix::cor_test(method = "spearman")
```


```{r}

```


# Model Assumptions
```{r}
mvnout <- mardia(data)
## Shapiro-Wilk Univariate normality test
mvnout$uv.shapiro
```

```{r}
## Mardia Multivariate normaility test
mvnout$mv.test
```


# SEM 
```{r}
model <- 'B =~ 1*b1 + b2 + b3 +b4 + b5 + b6 + b7 + b8 + b9 + b10 + b11 + b12 + b13 + b14 
          S =~ 1*s1 + s2 + s3 + s4 
          T =~ 1*t1 + t2 + t3 + t4 + t5 + t6 + t7
          I =~ S + T
          VLS =~ AGE + Sex + 1*PVL + ART + B + I
          VLS ~ AGE + Sex + PVL + ART + B + I'

## sem function syntax
fit_mod <- sem(model, data=data, std.lv = TRUE, estimator = "DWLS", se = 'robust')


```

## Model Fit
```{r}
# Chi-Square Statistics
fitMeasures(fit.mod, c("chisq", "df", "pvalue"))
```

```{r}
# RMSEA
fitMeasures(fit.mod, c("rmsea", "rmsea.ci.lower", "rmsea.ci.upper", "rmsea.pvalue"))
```

```{r}
# CFI and SRMR
fitMeasures(fit.mod, c("cfi", "srmr"))
```

```{r}
# Model Residuals
residuals(fit.mod)$cov
```


```{r}
summary(fit.mod, fit.measures = TRUE, standardized=TRUE)

standardizedsolution(fit.mod, type = "std.all", se = TRUE, zstat = TRUE, pvalue = TRUE, ci = TRUE)%>% 
  filter(op == "=~") %>% 
  select(LV=lhs, Item=rhs, Coefficient=est.std, ci.lower, ci.upper, SE=se, Z=z, 'p-value'=pvalue)

parameterEstimates(fit.mod, standardized=TRUE, rsquare = TRUE) %>% 
  filter(op == "r2") %>% 
  select(Item=rhs, R2 = est) 



```

```{r}
model2 <- 'B =~ 1*b1 + b2 + b3 +b4 + b8 + b9 + b10 + b12 + b14 
          VLS =~ AGE + Sex + 1*PVL + ART + B
          VLS ~ AGE + Sex + PVL + ART + B'

## sem function syntax
fit_model2 <- sem(model2, data=data, std.lv = TRUE, estimator = "DWLS", se = 'robust')

summary(fit_model2, fit.measures = TRUE, standardized=TRUE)

```


```{r}
lavaanPlot(model = fit.mod, coefs = TRUE)
```

